name: Build on Latest Platform with QMake
on: 
  push:
    branches:
      - master
      - commonlib
      - dev
    paths-ignore:
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - master
      - commonlib
      - dev
    paths-ignore:
      - 'docs/**'
      - '**.markdown'
      - '**.md'
      - 'LICENSE'
jobs:
    build:
        name: Build ${{ matrix.platforms.friendly_name }} Qt${{ matrix.qt.qt_ver }}
        runs-on: ${{ matrix.platforms.os }}
        strategy:
          fail-fast: false
          matrix:
              qt:
                - { qt_ver: 5.15.2, mingw_arch: win64_mingw81 }
                - { qt_ver: 6.3.1, mingw_arch: win64_mingw }
              platforms:
                - { os: windows-latest, generator: nmake, friendly_name: MSVC }
                - { os: windows-latest, generator: mingw32-make, friendly_name: MinGW }
                - { os: ubuntu-latest, generator: make, friendly_name: Ubuntu }
                - { os: macos-latest, generator: make, friendly_name: MacOS }
        steps:
          - name: Install Qt
            if: ${{ matrix.platforms.friendly_name != 'MinGW' }}
            uses: jurplel/install-qt-action@v2
            with:
              version: ${{ matrix.qt.qt_ver }}
          - name: Install Qt MinGW
            if: ${{ matrix.platforms.friendly_name == 'MinGW' }}
            uses: jurplel/install-qt-action@v2
            with:
              version: ${{ matrix.qt.qt_ver }}
              arch: ${{ matrix.qt.mingw_arch }}
          - name: Upgrade MinGW
            if: ${{ matrix.platforms.friendly_name == 'MinGW' }}
            run: |
              choco upgrade mingw
          - name: Git Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Set up MSVC environment
            if: ${{ matrix.platforms.friendly_name == 'MSVC' }}
            uses: ilammy/msvc-dev-cmd@v1
          - name: Install Linux Dependencies
            if: ${{ runner.os == 'Linux' }}
            run: |
              sudo apt-get update -y
              sudo apt-get install libxcb-icccm4 libxcb-xkb1 libxcb-icccm4 libxcb-image0 libxcb-render-util0 libxcb-randr0 libxcb-keysyms1 libxcb-xinerama0 libxcb-xinput-dev
          - name: ${{ matrix.platforms.friendly_name }} Qt${{ matrix.qt.qt_ver }}
            shell: pwsh
            run: |
              qmake QtSimpleChat.pro
              ${{ matrix.platforms.generator }}